### PR TITLE
Exclude videoclips

### PR DESCRIPTION
**Pull request by Mafarricos**

### CODE REVIEW

**Comment by schumi2004** [comment]
You sure this works?

23:24:06 T:2204   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: descriptor 'getAlbum' of 'xbmc.InfoTagMusic' object needs an argument
                                            Traceback (most recent call last):
                                              File "d:\users\kodi\AppData\Roaming\Kodi\addons\service.autosubs\default.py", line 110, in onPlayBackStarted
                                                videoclipAlbum = xbmc.InfoTagMusic.getAlbum()
                                            TypeError: descriptor 'getAlbum' of 'xbmc.InfoTagMusic' object needs an argument
                                            -->End of Python script error report<--

**Comment by Mafarricos** [comment]
When I made it it worked probably something changed in getAlbum since July?

**Comment by schumi2004** [comment]
I tested it in latest Helix but maybe i added content wrong, it failed here.

Anyway, i'm working on all the requests done in topic..
Only need to fix addon selection and then version 2.0 is done.

**Comment by Mafarricos** [comment]
Cool, when I have time I will check why is failing on Helix and provide a fix.

**Comment by schumi2004** [comment]
I need your help on this.
Can't get it to check on both include or exclude

code:
            if (xbmc.Player().isPlayingVideo() and totalTime > ExcludeTime and (not videoclipAlbum or liveTV or http) and ((not xbmc.getCondVisibility("VideoPlayer.HasSubtitles")) or (check_for_specific and not specific_language in availableLangs)) ):
                if all(movieFullPath.find (v) <= -1 for v in include_words) and (isInluded(movieFullPath)):
                    self.run = False
                    xbmc.sleep(1000)
                    Debug('Started: AutoSearching for Subs (included)')
                    xbmc.executebuiltin('XBMC.ActivateWindow(SubtitleSearch)')
                if all(movieFullPath.find (v) <= -1 for v in exclude_words) and (isExcluded(movieFullPath)):
                    self.run = False
                    xbmc.sleep(1000)
                    Debug('Started: AutoSearching for Subs (excluded)')
                    xbmc.executebuiltin('XBMC.ActivateWindow(SubtitleSearch)')
                else: pass

            else:
                Debug('Started: Subs found or source is Included/Excluded')
                self.run = False

It seems to pass to nested if statement.
Any ideas?

**Pull request merged**
